version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: webpacker
    versions:
    - 5.2.2
  - dependency-name: metadata_presenter
    versions:
    - 0.10.0
    - 0.11.0
    - 0.12.0
    - 0.13.1
    - 0.13.2
    - 0.13.4
    - 0.13.7
    - 0.14.0
    - 0.15.0
    - 0.15.1
    - 0.15.2
    - 0.16.0
    - 0.16.1
    - 0.18.0
    - 0.18.1
    - 0.19.0
    - 0.20.0
    - 0.21.0
    - 0.25.0
    - 0.26.0
    - 0.27.1
    - 0.27.2
    - 0.28.3
    - 0.28.6
    - 0.28.7
    - 0.3.1
    - 0.3.2
    - 0.4.0
    - 0.5.0
    - 0.6.0
    - 0.8.0
    - 0.8.1
    - 0.8.2
    - 0.9.0
  - dependency-name: faraday
    versions:
    - 1.3.1
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
  - dependency-name: rails
    versions:
    - 6.1.2
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - tomas-stefano
  - brenetic
  - njseeto
