version: '3.4'

services:
  runner-app-ci:
    build:
      context: .
      args:
        BUNDLE_ARGS: ''
    tty: true
    stdin_open: true
    ports:
      - 9000:3000
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      SECRET_KEY_BASE: '8917f6fa9a96e678f4777aea2bf148920a325162da1bd7b246baba4437eec8176765be27156161086abfe91266dfdc8a851d3e97edb66fe9f27ba4ea09bdc142'
      SERVICE_FIXTURE: 'version'
