version: '3.4'

services:
  runner-app:
    build:
      context: .
      args:
        BUNDLE_ARGS: ''
        SERVICE_FIXTURE: 'version'
    tty: true
    stdin_open: true
    ports:
      - 9000:3000
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      SERVICE_FIXTURE: 'version'
      USER_DATASTORE_URL: 'http://runner-app-datastore-app:3000/'
      SERVICE_SLUG: 'example-runner-service'
      ENCODED_PRIVATE_KEY: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMlNXWEwzRkVYdkF1eXYyN3UrVWZtQ2xqV1FwNzI5SUg4SUVTeUNCTkpPeTJwd0crCll4OGZHZDl4UldNVGhRaXA1ejMvd0Z0S1VsTWt2L2xYalE2Z3hTci9LWW9vMGNQb2dWK2V4aU5kOVNvcWJ1TW4KMjlVTUVqVEdIWm1ZV3Z1cVZCQXhpd3o1T0NzUURjdGI0SHNtWXJyRlpyczdQZnRHV2RpdVR3UTJoRDMyT2plOApaQkRpWUd5NzZKeTFpT1hCNlkwbC9UUHNnV2RsYldtcmZXSVAwTEF6Y1NIdzJEck9RRnBVaXdRU3lvcFlBalZ3Cm1TaG1POFhWa215dHo0cG9YQjZORzlUR2RISTdEcGR4K2E5M2RhV05rczJ4YkZJaFpZNmsyNEVSQzVYN2UzMzcKMGFwR1FYb21EYnk4VkZDY2wveTkxdHBCWGVHWUJDOGU5SWNDRFFJREFRQUJBb0lCQUNyYnIzNU9wY2J6TXRrZgp3Vmp4ZlEza1JWYUNxaldWdTdsdFVFNnRpV3hiU0NXb1EzSis1djJOUzJiOWloRzh4d1A4Q2FsbW0wR3FaVnQ2CmxCd2tJZmtvWmxwRmlZNzFVc09PSXVGS2c3WHF6NXM1UEZtNEwveTc2OHBWMFd0THRxK0d6ckI2TEFvNC9aOHIKWHdQc2FvUWNCdkFpeml1S2w3VU4va0ZjUElKVzkxcjBDWThJYjFVUDZRWGtwWTVsa2I0UWlGRHFiVEl6VjU2OAovaSt1QVY2YVRnWXV5V3B5bmJHZU13cFZOZHV4OUR5YUVkMTFmSUMrczVteWw3ZmMwVWRBRGxwdStHK29Db2RyClpMSWlpd0NrTTdUM0M4N1ZEajVnZkpIdVU0dnpmSG1EbnhlbDI2bWpJMEtIclRkVEVrMldQcys4Z1dZaVo1bWoKYnV2eFRhVUNnWUVBN0xRMDlMK2ZsOUhzbExzOFJyWmhTbHZEb1dMcHdueGVGd282TWFhZ1Nxby9vZVh0bFFzegpDbytveHVtem1IQnIwRE5PeCtKcDVtZHFuS0Nvb0F2aThyMFUrbEFXeTErSm9vaUkrMjlTT1M0aGRpM1dFQVQyCnZXYTQ4eEtOOWVhU083czZvTnNXU0hJdEdlVFU4SXh6ZmRjTHJUeStOZnhiZytMc3ZyNmFHZWNDZ1lFQTZ0aysKd2MxelBrdkhpZGN4T01xVUk1RWxjTnlucCtaRkk0U1p5ODBPTHVjVEZQelpoazdTSUpYMUtyNFE3S1lBcjhhTApCQ2luMjkvRmwvbGhzK2NtS1F3bzZTelAxY2hUcEtCMXB3VEV1cVRlQ1NsRER6cFZwazZ5cFN0dTJmSlpMZkxqCkkxTWFiV2NrdkJkRnp6NkJ0aTd6VUN3QkpUeEh6UC9QdHNVcmplc0NnWUE5Q0JJSGNVa3pHaHVJRmVicXpLZTEKUm9mZ211SnZGU1lsaHF1T2xjb0t0bThGellVK3dzNThVS0pSOTN3cE9BTjBnV1kwdjdwU2dDUExFdG1udXFqZgpzY1V3N1dtVE1xVUlWWEFNZEoyY3hMbzRBSVdMUjl4ZTVaZVdoUmc1YVNRWFpxVXRTSkFzU2RRN012ZDh0cG9vCnZrUHlmUkVHVm5VNlFrNk11QlIvelFLQmdFZFY5QVVrWmdRZk9wNDVHbjk0c1dUWVd2b2NYR1RZd2xtV2xxemMKUFptcm9SVTM5TThpTkJ1bjBVL0phaFNvRy85SW5NT0hvZTFjM0lWY1AveElrMFBXcUxxalhRSkFGb0FrS1hpeApMeHpPcFk4ODFGelV5RjE2L0RMRnJhZFFRUngrOGRXeUVZMzN6YVhBbi9qaXNMM3BKd2xNUkpETjdiVnNZdWpPCm5Ycy9Bb0dBVjFEVTlqUDA2YWxuU3VudW1wR1ZaV3FqSkVGcVlnNmRoalJYVTFYWXZ2bVVSWGR0SHVVY3hYWG4KaXd1WkkwQi9LMmxhdFAydEVJUEZ4MU82dldJUUlTbElKb0x5VlRqck5FUmY2K05XMkkrWjlUQi93ZVlTckpRaQpEMDFwN1NLbkdDdVE0QXhRYXVZZzErRUlwbHJNRnQwRmNhRkdIbnBXeEpFZVFqL3g1MlU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=='
    links:
      - runner-app-service-token-cache-app
      - runner-app-datastore-app

  runner-app-datastore-db:
    image: postgres:10.9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: datastore_local

  runner-app-datastore-app:
    container_name: runner-app-datastore-app
    build:
      context: https://github.com/ministryofjustice/fb-user-datastore.git
    environment:
      SENTRY_DSN: sentry-dsn
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      MAX_IAT_SKEW_SECONDS: '60'
      SERVICE_TOKEN_CACHE_ROOT_URL: 'http://runner-app-service-token-cache-app:3000'
      DATABASE_URL: postgres://postgres:password@runner-app-datastore-db/datastore_local
    ports:
      - 9001:3000

  runner-app-service-token-cache-app:
    container_name: runner-app-service-token-cache-app
    build:
      context: https://github.com/ministryofjustice/fb-service-token-cache.git
    environment:
      SENTRY_DSN: sentry-dsn
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 'true'
      REDIS_URL: runner-app-service-token-cache-redis
      SERVICE_TOKEN_CACHE_TTL: 999999
      KUBECTL_SERVICES_NAMESPACE: 'formbuilder-services-test-dev'
    depends_on:
      - runner-app-service-token-cache-redis
    ports:
      - 9002:3000

  runner-app-service-token-cache-redis:
    container_name: runner-app-service-token-cache-redis
    image: redis:5.0.6-alpine
