version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: Setup containers
          command: make setup
      - run:
          name: security
          command: docker-compose run --rm runner-app bundle exec brakeman -q --no-pager
      - run:
          name: test
          command: docker-compose run --rm runner-app bundle exec rspec
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: main
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
